#!/bin/bash

# This file is responsible for detecting which Pi we're on by querying the
# hostname, then running the sd-submarine or sd-surface script.  This will be
# called by our init.d script.

MY_HOSTNAME=`hostname -s`

if [ $MY_HOSTNAME = "pi-surface" ]; then
    /usr/bin/sd-surface 2>&1 > /tmp/surface-log &
else
    /usr/bin/sd-submarine 2>&1 > /tmp/submarine-log &
fi
