#!/bin/bash

# This script is responsible for mounting inserted thumbdrives, then checking 
# for the existence of an update package, and finally extracting and running the
# update script if it exists.

